# Description

Our model uses a pipeline that employs zero-shot classification with the 'valhalla/distilbart-mnli-12-3' model. Rather than dividing the dataset into training and testing sets, we use all descriptions from the dataset (column '**busdesc**') as input. To prevent any potential disruption to the model, we also change the names of the sectors and labels.

From our previous work, we got 42 different verticals. To check the efficiency of the model, we labelled 241 companies mannually for these verticals, i.e. at least 5 companies for each vertical, then applied Zero-Shot classification to this dataset. However, there is no observed data for the label '**Ephemeral content**', so we just leave it here without supported data.

As a result, the precision is 0.7, the recall and the F1 Score are both 0.6 with weighted average for this model.

# Preprocessing the dataset

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_excel("/content/drive/MyDrive/related_company_after_trans.xlsx")
data

CompanyID                                       Company Name  \
0             3                                                 90   
1             8                                               1871   
2            12                                               Nova   
3            19                                      .org/advisors   
4            36  (Re)pensar Direitos Humanos [(Re)think Human R...   
...         ...                                                ...   
21650    167369                                       VitaMania.su   
21651    167374                                 Instrat Foundation   
21652    167375                                           DelphCap   
21653    167386                                      Ikigai Growth   
21654    167392                                      Traders Brawl   

                                             Description  \
0      90* is a  social consultancy + research initia...   
1      The story of the Great Chicago Fire of 1871 is...   
2      Nova is the global top-talent community that c...   
3      Planning. Systems. Culture. Only when all thre...   
4      (Re)pensar Direitos Humanos é um projeto que c...   
...                                                  ...   
21650  VitaMania has attracted more than 500k $ in ge...   
21651  Warsaw based think tank\nEnergy & climate | Ju...   
21652  DelphCap is a London-based ESG and Impact advi...   
21653  En Ikigai Growth somos expertos en ayudar a ne...   
21654  Traders Brawl is a social media marketing agen...   

                                Industries  \
0                                 Research   
1                                 Internet   
2                                 Internet   
3                    Management Consulting   
4       Non-profit Organization Management   
...                                    ...   
21650                               Retail   
21651                          Think Tanks   
21652  International Trade and Development   
21653                Management Consulting   
21654            Marketing and Advertising   

                                                 Tagline  \
0                                                    NaN   
1      World #1 Private Business Incubator. \n\nSuppo...   
2      The Global Top Talent Network | Connecting the...   
3                                                    NaN   
4      Um convite para perceber e (re)pensar os Direi...   
...                                                  ...   
21650  Online selection of vitamin recipe and shop, a...   
21651  Energy & climate | Just transition | Sustainab...   
21652  Your partners in client-focused, integrated ES...   
21653  Fórmulas de crecimiento para negocios en Inter...   
21654  Traders Brawl is a Fintech, Web3 & Blockchain ...   

                                             Specialties  \
0      consultancy, research, Turkey, Data, Knowledge...   
1                                                    NaN   
2      Employer Branding, Recruitment, Headhunting, T...   
3      nonprofit, management consulting, strategic pl...   
4                                                    NaN   
...                                                  ...   
21650                                                NaN   
21651  public policy, economics, energy, inequalities...   
21652  Investment Sourcing, Africa Focused, ESG and I...   
21653                                                NaN   
21654  Blockchain, fitness, crypto, Web3, wealth crea...   

                                                 busdesc  gind  
0      90 90 is a  social consultancy  research initi...   NaN  
1      1871 the story of the great chicago fire of 18...   NaN  
2      nova nova is the global toptalent community th...   NaN  
3      orgadvisors planning systems culture only when...   NaN  
4      rethinking human rights rethinking human right...   NaN  
...                                                  ...   

In [ ]:
data.dropna(subset=['gind'], how='any', inplace=True)

# Installing valhalla/distilbart-mnli-12-3

In [ ]:
!pip install transformers

In [ ]:
from transformers import pipeline
classifier = pipeline("zero-shot-classification", model='valhalla/distilbart-mnli-12-3', device=0, batch_size=8)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.39k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.02G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

# Changing the names of the sectors and labels

The following labels and sectors are from column 'class_name' in the table 'merged_df', which is clustered and grouped in our previous study.

In [ ]:
labels = [
    "Beauty, Femtech",
    "Autonomous cars",
    "Cybersecurity",
    "Gaming, eSports",
    "Supply chain technology",
    "Digital health, Lifestyles of Health and Sustainability (LOHAS) and wellness, Wearables and quantified self",
    "Mortgage tech, Real estate tech",
    "Legal tech",
    "Mobile",
    "Robotics and drones",
    "Cleantech",
    "B2B payments, Mobile commerce",
    "Oncology",
    "Pet tech",
    "3D printing, Advanced manufacturing, Construction technology, Industrials, Infrastructure, Manufacturing",
    "Oil and gas",
    "Cannabis",
    "Adtech, Marketing tech",
    "Ecommerce",
    "HRtech",
    "Audiotech",
    "Life sciences",
    "Cloudtech and DevOps, Software as a service (SaaS)",
    "Ephemeral content",
    "Carsharing, Micro-mobility, Mobility tech, Ridesharing",
    "Impact investing",
    "Space tech",
    "Agtech",
    "Insurtech",
    "Big Data",
    "Internet of Things (IoT)",
    "Restaurant tech",
    "Climate tech",
    "Foodtech",
    "Healthtech",
    "Fintech",
    "Nanotechnology",
    "Media and telecommunications (TMT), Technology",
    "Edtech",
    "Artificial intelligence and machine learning (AI/ML)",
    "Augmented reality (AR), Virtual reality (VR)",
    "Cryptocurrency and blockchain"
]


In [ ]:
sector = {
    1: "Beauty, Femtech",
    2: "Autonomous cars",
    3: "Cybersecurity",
    4: "Gaming, eSports",
    5: "Supply chain technology",
    6: "Digital health, Lifestyles of Health and Sustainability (LOHAS) and wellness, Wearables and quantified self",
    7: "Mortgage tech, Real estate tech",
    8: "Legal tech",
    9: "Mobile",
    10: "Robotics and drones",
    11: "Cleantech",
    12: "B2B payments, Mobile commerce",
    13: "Oncology",
    14: "Pet tech",
    15: "3D printing, Advanced manufacturing, Construction technology, Industrials, Infrastructure, Manufacturing",
    16: "Oil and gas",
    17: "Cannabis",
    18: "Adtech, Marketing tech",
    19: "Ecommerce",
    20: "HRtech",
    21: "Audiotech",
    22: "Life sciences",
    23: "Cloudtech and DevOps, Software as a service (SaaS)",
    25: "Carsharing, Micro-mobility, Mobility tech, Ridesharing",
    26: "Impact investing",
    27: "Space tech",
    28: "Agtech",
    29: "Insurtech",
    30: "Big Data",
    31: "Internet of Things (IoT)",
    32: "Restaurant tech",
    33: "Climate tech",
    34: "Foodtech",
    35: "Healthtech",
    36: "Fintech",
    37: "Nanotechnology",
    38: "Media and telecommunications (TMT), Technology",
    39: "Edtech",
    40: "Artificial intelligence and machine learning (AI/ML)",
    41: "Augmented reality (AR), Virtual reality (VR)",
    42: "Cryptocurrency and blockchain"
}


In [ ]:
data

CompanyID                     Company Name  \
31          211                        22 Eleven   
75          418          99bros | Simply Insured   
109         667                            Abloh   
115         711                  abtira | garden   
155         994                           Acumen   
...         ...                              ...   
21259    164493                         SkyGrids   
21428    165520  Panel iQ Technologies Pvt. Ltd.   
21528    166317          The Climate Consultancy   
21617    167103                             HYRD   
21626    167153                  The Goose House   

                                             Description  \
31     22 Eleven is an eCommerce retailer building a ...   
75     99bros is a digital insurance brokerage platfo...   
109    A web and mobile-based platform for students a...   
115    The idea behind our line is natural, as much a...   
155    Acumen is changing the way the world tackles p...   
...                                                  ...   
21259  SkyGrids is revolutionising the drone industry...   
21428  PanelIQ Technologies is staffing agency and an...   
21528  The Climate Consultancy is an impact strategy ...   
21617  HYRD is a revolutionary AI-driven hiring tool ...   
21626  A UK grassroots esports organisation. A group ...   

                                 Industries  \
31                                   Retail   
75                                Insurance   
109    Technology, Information and Internet   
115                               Cosmetics   
155        Venture Capital & Private Equity   
...                                     ...   
21259                       Defense & Space   
21428               Staffing and Recruiting   
21528   Information Technology and Services   
21617                       Human Resources   
21626                        Computer Games   

                                                 Tagline  \
31                      Building global eCommerce brands   
75               Who says Insurance must be complicated?   
109                    The Next Wave in Higher Education   
115    We deliver natural, minimalist products for yo...   
155    Changing the way the world tackles poverty by ...   
...                                                  ...   
21259                Limitless drones. Boundless flight.   
21428  A Tech Talent Company that is Building an Eco-...   
21528                 Collective action for the climate.   
21617  HYRD is an AI-driven platform that matches can...   
21626  The Goose House is a gaming community comprise...   

                                             Specialties  \
31                                                   NaN   
75     Insurtech, Insurance, Pension, Motor, Life, No...   
109                                                  NaN   
115            skincare, bodycare, organic , and natural   
155    non-profit, poverty, social enterprise, impact...   
...                                                  ...   
21259                                                NaN   
21428                                                NaN   
21528  Content marketing, Social Media, Thought Leade...   
21617                                                NaN   
21626                                                NaN   

                                                 busdesc  gind  
31     22 eleven 22 eleven is an ecommerce retailer b...  19.0  
75     99bros  simply insured 99bros is a digital ins...  29.0  
109    abloh a web and mobilebased platform for stude...  39.0  
115    abtira  garden the idea behind our line is nat...   1.0  
155    acumen acumen is changing the way the world ta...  26.0  
...                                                  ...   ...  
21259  skygrids skygrids is revolutionising the drone...  10.0  
21428  panel iq technologies pvt ltd paneliq technolo...  20.0  
21528  the climate consultancy the climate consultanc...  33.0  
216

# Predictions

In [ ]:

preds = classifier(list(data["busdesc"]), labels)

In [ ]:
result = []
for item in preds:
  result.append(item["labels"][0])

In [ ]:
import math

true = []
for item in data["gind"]:
  key = item
  true.append(sector[key])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

print(confusion_matrix(true, result))
print(classification_report(true, result))
print("F1 score is: "+ (str)(f1_score(true, result, average='micro')))

[[1 0 0 ... 0 0 1]
 [0 5 0 ... 0 0 0]
 [0 0 4 ... 0 0 0]
 ...
 [0 0 1 ... 6 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 4]]
                                                                                                             precision    recall  f1-score   support

   3D printing, Advanced manufacturing, Construction technology, Industrials, Infrastructure, Manufacturing       1.00      0.14      0.25         7
                                                                                     Adtech, Marketing tech       0.83      1.00      0.91         5
                                                                                                     Agtech       0.67      0.67      0.67         6
                                                       Artificial intelligence and machine learning (AI/ML)       0.40      0.67      0.50         6
                                                                                                  Audiotech       0.00      0.00      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [ ]:
# Calculating the total data size from the confusion matrix
conf_matrix = confusion_matrix(true, result)
data_size = conf_matrix.sum()
data_size


241

# Add Unknown (In Further Research)

In [ ]:
data1 = pd.read_excel("/content/drive/MyDrive/498 capstone/merged_df.xlsx")
data1.head()

Unnamed: 0  New_class_byhand               class_name  \
0           0                 1           Beauty,Femtech   
1           1                 2          Autonomous cars   
2           2                 3            Cybersecurity   
3           3                 4           Gaming,eSports   
4           4                 5  Supply chain technology   

                                            keywords  \
0  companies    in    the    beauty    vertical  ...   
1  autonomous    car    technologies    are    ha...   
2  cybersecurity    companies    provide    infor...   
3  esports    refers    to    competitive    onli...   
4  supply    chain    technology    companies    ...   

                                        top_keywords  \
0   bespoke, clean, digital, female, femtech, fer...   
1   autonomous, cars, driver, lidar, mobility, te...   
2   cloud based, cybersecurity, data, detect, mal...   
3   broadcast, consoles, electronic, gambling, ga...   
4   chains, delivery, demand, freight, last mile ...   

                                  generated ketwords  \
0   OBGYN tech, acne treatment, anti-aging, beaut...   
1   applications of driverless technology, autono...   
2   artificial intelligence in security, blockcha...   
3   AR gaming experiences, adaptive gaming techno...   
4   AI for supplier selection, IoT in logistics, ...   

                                    combine_keywords  
0  OBGYN tech,acne treatment,anti-aging,beauty,be...  
1  applications of driverless technology,autonomo...  
2  artificial intelligence in security,blockchain...  
3  AR gaming experiences,Next-gen game consoles,P...  
4  AI for supplier selection,IoT in logistics,Ven...

In [ ]:
name = labels

In [ ]:
from transformers import pipeline

summarizer = pipeline("summarization", model="Falconsai/text_summarization")

config.json:   0%|          | 0.00/1.49k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

In [ ]:
summaries = []
for keywords in data1['combine_keywords']:
    summary = summarizer(keywords, max_length=30, min_length=1, do_sample=False)[0]['summary_text']
    summaries.append(summary)

data1['label'] = summaries

label_dic = dict(zip(summaries, name))

Token indices sequence length is longer than the specified maximum sequence length for this model (719 > 512). Running this sequence through the model will result in indexing errors


In [ ]:
label_dic

{'OBGYN tech,acne treatment,anti-aging,beauty blog,beeauty tips,bespoke': 'Beauty, Femtech',
 'applications of driverless technology,autonomous driving platforms . autonomous vehicles industry insights . autonomous vehicle technology .': 'Autonomous cars',
 'artificial intelligence in security,blockchain security,cloud based,cloud security,compliance frameworks,cyber forensics,': 'Cybersecurity',
 'AR gaming experiences,Next-gen game consoles,Player performance analytics,adaptive gaming technology,anti-cheating technology,blockchain': 'Gaming, eSports',
 'AI for supplier selection,IoT in logistics,Vendor managed inventory,blockchain verified origin,carbon-neutral shipping options,': 'Supply chain technology',
 'AI medical imaging,Advanced heart rate monitors,Genomic data analysis,Sustainable travel technologies,UV exposure track': 'Digital health, Lifestyles of Health and Sustainability (LOHAS) and wellness, Wearables and quantified self',
 'AI-driven property recommendations,Automated

In [ ]:
data = data.reset_index(drop=True, inplace=True)
results = data.copy()
results['1st_pred'] = results['busdesc']
results['1st_prob'] = results['busdesc']
results['2nd_pred'] = results['busdesc']
results['2nd_prob'] = results['busdesc']
results['3rd_pred'] = results['busdesc']
results['3rd_prob'] = results['busdesc']
results['4th_pred'] = results['busdesc']
results['4th_prob'] = results['busdesc']
results['5th_pred'] = results['busdesc']
results['5th_prob'] = results['busdesc']

for i in range(241):
  pred = classifier(data["busdesc"].iloc[i], list(data1['combine_keywords']))
  results.loc[i, '1st_pred'] = label_dic[pred['labels'][0]]
  results.loc[i, '1st_prob'] = str("{:.3f}".format(pred['scores'][0]))
  results.loc[i, '2nd_pred'] = label_dic[pred['labels'][1]]
  results.loc[i, '2nd_prob'] = str("{:.3f}".format(pred['scores'][1]))
  results.loc[i, '3rd_pred'] = label_dic[pred['labels'][2]]
  results.loc[i, '3rd_prob'] = str("{:.3f}".format(pred['scores'][2]))
  results.loc[i, '4th_pred'] = label_dic[pred['labels'][3]]
  results.loc[i, '4th_prob'] = str("{:.3f}".format(pred['scores'][3]))
  results.loc[i, '5th_pred'] = label_dic[pred['labels'][4]]
  results.loc[i, '5th_prob'] = str("{:.3f}".format(pred['scores'][4]))



In [ ]:
results

CompanyID                     Company Name  \
0         211                        22 Eleven   
1         418          99bros | Simply Insured   
2         667                            Abloh   
3         711                  abtira | garden   
4         994                           Acumen   
..        ...                              ...   
236    164493                         SkyGrids   
237    165520  Panel iQ Technologies Pvt. Ltd.   
238    166317          The Climate Consultancy   
239    167103                             HYRD   
240    167153                  The Goose House   

                                               busdesc  gind  \
0    22 eleven 22 eleven is an ecommerce retailer b...    19   
1    99bros  simply insured 99bros is a digital ins...    29   
2    abloh a web and mobilebased platform for stude...    39   
3    abtira  garden the idea behind our line is nat...     1   
4    acumen acumen is changing the way the world ta...    26   
..                                                 ...   ...   
236  skygrids skygrids is revolutionising the drone...    10   
237  panel iq technologies pvt ltd paneliq technolo...    20   
238  the climate consultancy the climate consultanc...    33   
239  hyrd hyrd is a revolutionary aidriven hiring t...    20   
240  the goose house a uk grassroots esports organi...     4   

                                              1st_pred 1st_prob  \
0                                            Ecommerce    0.078   
1    Artificial intelligence and machine learning (...    0.191   
2                                  Robotics and drones    0.063   
3                                               Mobile    0.116   
4                                     Impact investing    0.079   
..                                                 ...      ...   
236                                    Autonomous cars    0.085   
237                                             Mobile    0.065   
238                                  Ephemeral content    0.092   
239                                       Climate tech    0.094   
240                                           Pet tech    0.074   

                                              2nd_pred 2nd_prob  \
0    Carsharing, Micro-mobility, Mobility tech, Rid...    0.057   
1                                            Insurtech    0.065   
2       Media and telecommunications (TMT), Technology    0.055   
3                                  Robotics and drones    0.049   
4                                               Mobile    0.068   
..                                                 ...      ...   
236  Artificial intelligence and machine learning (...    0.081   
237                      Cryptocurrency and blockchain    0.043   
238       Augmented reality (AR), Virtual reality (VR)    0.060   
239                      Cryptocurrency and blockchain    0.079   
240                                             HRtech    0.056   

                                              3rd_pred 3rd_prob  \
0                                             Pet tech    0.057   
1         Augmented reality (AR), Virtual reality (VR)    0.056   
2    Artificial intelligence and machine learning (...    0.054   
3                                            Audiotech    0.049   
4                                             Pet tech    0.048   
..                                                 ...      ...   
236  3D printing, Advanced manufacturing, Construct...    0.050   
237       Augmented reality (AR), Virtual reality (VR)    0.042   
238                                           Pet tech    0.058   
239                                             Mobile    0.060   
240                            Supply chain technology    0.054   

                                              4th_pred 4th_prob  \
0                                    Ephemeral content    0.055   
1                                               Agtech    0.045   
2                 

In [ ]:
results.to_csv('/content/drive/MyDrive/498 capstone/ZeroShot_labelled_Result_Verticals_all.csv', index=False)
